# Generated by Django 3.0.4 on 2020-11-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_auto_20201115_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspect',
            old_name='case_id',
            new_name='case',
        ),
    ]
