# Generated by Django 3.0.4 on 2020-11-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0003_auto_20201116_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminal_record',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='criminal_record',
            old_name='suspect_id',
            new_name='suspect',
        ),
    ]
