# Generated by Django 3.0.4 on 2020-11-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0004_auto_20201116_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
